In [32]:
import numpy as np
from scipy.sparse import lil_matrix

In [57]:
def words_to_dict(words):
    words = set(words)
    words = sorted(list(words))
    word2id = {word: idx for idx, word in enumerate(words)}
    return word2id, {idx: word for word, idx in word2id.items()}

def get_coocurrence_matrix(text):
    text = " ".join(text.split('.'))
    words = [x.strip() for x in text.split()]
    word2id, id2word = words_to_dict(words)
    num_words = len(word2id.keys())
    mat = lil_matrix((num_words, num_words), dtype=np.int8)
    for word1, word2 in zip(words[:-1], words[1:]):
        if word2 < word1:
            tmp = word1
            word1 = word2
            word2 = tmp
        mat[word2id[word1], word2id[word2]] += 1
        # Create symmetric matrix
        #mat[word2id[word2], word2id[word1]] += 1
    return word2id, id2word, mat
    
word2id, id2word, mat = get_coocurrence_matrix(
    'yes. this is a nice cafe.'
    'cafe is this. this is cafe cafe.'
)
print(', '.join(sorted(word2id.keys())))
print(mat.toarray())

a, cafe, is, nice, this, yes
[[0 0 1 1 0 0]
 [0 2 2 1 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 1]
 [0 0 0 0 0 0]]
